os: linux
dist: xenial
language: go
go: 1.13
go_import_path: github.com/freedge/gomeme
env:
  global: TMPDIR=/tmp
services:
  - docker
jobs:
  include:
  - stage: build
    env: GOOS=linux GOARCH=amd64
    install: true
    script: 
    - go get ./...
    - go install
    - tar zcvf /home/travis/gomeme-${TRAVIS_TAG}.tar.gz -C /home/travis/gopath/bin/ gomeme
  - stage: test
    install: true
    script: 
    - go get ./...
    - go test ./...
    - gofmt -s -d . | tee /home/travis/gofmt.out ; test ! -s /home/travis/gofmt.out
  - stage: integrationtest
    install: true
    env:
      - GOMEME_PASSWORD=workbench
      - GOMEME_ENDPOINT=https://workbench:8443/automation-api
      - GOMEME_CERT_DIR=.certs
    addons:
      hosts:
        - workbench
    before_install:
    # set up a running workbench
    - curl -L https://controlm-appdev.s3-us-west-2.amazonaws.com/workbench/9.0.19.140/deploy/ova/controlm-workbench-9.19.140.xz | docker load
    - docker run -dt --hostname=workbench --name=workbench -p 127.0.0.1:8443:8443 -p 7005:7005 controlm-workbench:9.19.140
    - sleep 60
    
    - until curl --fail -L -k --connect-timeout 3 --max-time 3 ${GOMEME_ENDPOINT}/startHere.html -o /dev/null ; do echo . ; sleep 1 ; done
    # get a certificate to connect to it
    - mkdir .certs
    - echo | openssl s_client -connect workbench:8443 -showcerts
    - echo | openssl s_client -connect workbench:8443 -showcerts | grep -A 40 "BEGIN CERTIFICATE" -m 1 | grep -B 40 "END CERTIFICATE" > .certs/cert.pem
    # set up bats for our testing
    - curl -L https://github.com/bats-core/bats-core/archive/v1.1.0.tar.gz | tar zxf - -C ~/
    - ~/bats-core-1.1.0/install.sh /home/travis/gopath
    script: 
    - go get ./...
    - bats tests.bats
deploy:
  provider: releases
  api_key:
    secure: WZmUO8HvbBpKgNV9es0Y4/vEflqrSOSQIPgpzdEWZF5zY2Ul+lPQaZ8XrNcKY5PdvkX5DqhRGFPNg6RcVmiAKsAJ25fa69HR+/lS6EVcG+MU4PVsawE72tJcnS6yvm9l6JryUv182tl5JpCWRDrDWsfZh05rBJ1w6Vbh53bivEaNy0mFrpbCPhasyq915cISYs+WGUTwRZ4AB8iCWjCHIOR4nZoGGOy26ujIfepY8VjvlXAOk38JRaW4VrOEeUqQcmHy38HTD8njbRpjGzi6SPE1GIsO3cYJcJIy16civ7pimo3xmmvkQWawzZIBqAdcVbgRE8wpLHXAqaom1kuW+eQ79/sQLwdxQc6MRfhu2GznPaysz4XN1Na5nwfo0jKcj5QGsMB6Rp5BxeAtLtRdqWavs6l5Apt8stefUQjcPaDDqiJtXO8/35Dijr+TQ6R3Yo+ncrNUmMeL7NnUxPXDexBC84R+RP/iE8pQOuyhO+ZLsG773Zlzs87izfRP3zfVXhUKNHGjcmHkXyKZ8yP6JKC4Hwb0H81K6PRTbeaAQ/lWJsHEAAzOI/yNHLnKGxrJCKWmd1dEsgwtti7Zuu9qa73F3N0lOa5qvJ5nHE1O/edMA0mJdtYl+LZ6GUZ9QO2P9t97x5xsN+1GkLnSbVCHV2wciZ7VL1/z+8m/pTmGcPc=
  file: /home/travis/gomeme-${TRAVIS_TAG}.tar.gz
  cleanup: false
  on:
    tags: true
