apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: httpd
  name: httpd
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: httpd
    deploymentconfig: httpd
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: httpd
        deploymentconfig: httpd
    spec:
      containers:
      - image: centos/httpd-24-centos7
        imagePullPolicy: IfNotPresent
        name: daemon
        command: ["bash"]
        env:
        - name: RELEASE_PATH
          value: "https://github.com/freedge/gomeme/releases/latest/download"
        args: [ "-c" , 
         "echo AddType application/appinstaller .appinstaller > /data/.htaccess; while true ;  do  curl -L -o /data/gomeme.appinstaller ${RELEASE_PATH}/gomeme.appinstaller; curl -L -o /data/gomemepkg.msix ${RELEASE_PATH}/gomemepkg.msix; sleep 36000 ; done" ]
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: levolume
      - image: centos/httpd-24-centos7
        imagePullPolicy: IfNotPresent
        name: httpd
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/rh/httpd24/root/var/www/html
          name: levolume
          readOnly: true
        - mountPath: /run/httpd/
          name: runhttpd
      volumes:
      - name: levolume
        emptyDir: {}
      - name: runhttpd
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
