name: Go
on: [push]
env:
  GOMEME_PASSWORD: workbench
  GOMEME_ENDPOINT: https://workbench:8443/automation-api
  GOMEME_CERT_DIR: .certs
  GZIP: "-1"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v1
      with:
        go-version: 1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - name: Cache Container Images
      id: cache-container-images
      uses: jamesmortensen/cache-container-images-action@v1
      with:
        images: |
          controlm/workbench:latest

    - name: Prepare tests
      timeout-minutes: 5
      run: |
        echo HOME=${HOME} pwd=$(pwd) id=$(id)
        echo "127.0.0.1 workbench" | sudo tee -a /etc/hosts
        sudo apt-get install -y libxml2-utils awscli podman openssl bats npm
        podman pull controlm/workbench:latest
        mkdir .certs

    - name: Run tests
      timeout-minutes: 15
      run: |
        podman run -dt --hostname workbench --name=workbench -p 127.0.0.1:8443:8443 -p 7005:7005 controlm/workbench:latest
        sleep 180
        until curl -s --fail -L -k --connect-timeout 3 --max-time 3 ${GOMEME_ENDPOINT}/swagger-ui.html -o /dev/null ; do echo . ; sleep 10 ;done
        echo | openssl s_client -connect workbench:8443 -showcerts
        echo | openssl s_client -prexit -connect workbench:8443 | openssl x509 > .certs/cert.pem
        until curl --cacert .certs/cert.pem -o ctm-cli.tgz ${GOMEME_ENDPOINT}/ctm-cli.tgz --fail ; do echo . ; sleep 10 ; done
        sudo npm -g install ctm-cli.tgz

        export "PATH=${PATH}:."
        bats tests.bats

